import { Player } from './Player';

export interface PlayerResponse {
  success: boolean;
  player: Player | null;
}

//#region - autogenerated - do not modify
export * from './Player';
export * from './Player/Stats/Arcade';
export * from './Player/Stats/TrueCombat';
export * from './Player/Stats/SpeedUHC';
export * from './Player/Stats/VampireZ';
export * from './Player/Stats/TNTGames';
export * from './Player/Stats/Quake';
export * from './Player/Stats/UHC';
export * from './Player/Stats/Duels';
export * from './Player/Stats/SkyClash';
export * from './Player/Stats/Housing';
export * from './Player/Stats/SuperSmash';
export * from './Player/Stats/Skywars';
export * from './Player/Stats/Pit';
export * from './Player/Stats/Arena';
export * from './Player/Stats/Battleground';
export * from './Player/Stats/Paintball';
export * from './Player/Stats/Mcgo';
export * from './Player/Stats/Walls';
export * from './Player/Stats/Bedwars';
export * from './Player/Stats/BuildBattle';
export * from './Player/Stats/Gingerbread';
export * from './Player/Stats/Legacy';
export * from './Player/Stats/Walls3';
export * from './Player/FireworkStorage';
export * from './Player/Tourney';
export * from './Player/HousingMeta';
export * from './Player/AchievementTotem';
export * from './Player/ParkourCompletionBests';
export * from './Player/Stats';
export * from './Player/PetStats';
export * from './Player/SocialMedia';
export * from './Player/GiftingMeta';
export * from './shared/util';
//#endregion - do not modify
