import { IndexType } from '../../shared/util'

export type Arena = IndexType & {
  active_rune?: string
  coins?: number
  coins_spent?: number
  damage_1v1?: number
  damage_2v2?: number
  damage_4v4?: number
  damage_ffa?: number
  deaths_1v1?: number
  deaths_2v2?: number
  deaths_4v4?: number
  games_1v1?: number
  games_2v2?: number
  games_4v4?: number
  games_ffa?: number
  hat?: string
  healed_1v1?: number
  healed_2v2?: number
  healed_4v4?: number
  healed_ffa?: number
  keys?: number
  kills_1v1?: number
  kills_2v2?: number
  kills_4v4?: number
  kills_ffa?: number
  losses_1v1?: number
  losses_2v2?: number
  losses_4v4?: number
  lvl_cooldown?: number
  lvl_damage?: number
  lvl_energy?: number
  lvl_health?: number
  magical_chest?: number
  offensive?: string
  packages?: string[]
  rating?: number
  rune_level_damage?: number
  rune_level_energy?: number
  rune_level_slowing?: number
  rune_level_speed?: number
  rune_level_tank?: number
  selected_sword?: string
  support?: string
  ultimate?: string
  utility?: string
  win_streaks_1v1?: number
  win_streaks_2v2?: number
  win_streaks_4v4?: number
  win_streaks_ffa?: number
  wins?: number
  wins_1v1?: number
  wins_2v2?: number
  wins_4v4?: number
  wins_ffa?: number
}
