import { IndexType } from '../../shared/util'

export type Battleground = IndexType & {
  afk_warned?: number
  aquamancer_plays?: number
  assists?: number
  autostrikemode?: boolean
  avenger_plays?: number
  berserker_plays?: number
  bound_weapon?: IndexType
  broken_inventory?: number
  chosen_class?: string
  coins?: number
  crafted?: number
  crafted_epic?: number
  crafted_legendary?: number
  crafted_rare?: number
  crusader_plays?: number
  cryomancer_plays?: number
  current_weapon?: number
  damage?: number
  damage_aquamancer?: number
  damage_avenger?: number
  damage_berserker?: number
  damage_crusader?: number
  damage_cryomancer?: number
  damage_defender?: number
  damage_earthwarden?: number
  damage_mage?: number
  damage_paladin?: number
  damage_prevented?: number
  damage_prevented_aquamancer?: number
  damage_prevented_avenger?: number
  damage_prevented_berserker?: number
  damage_prevented_crusader?: number
  damage_prevented_cryomancer?: number
  damage_prevented_defender?: number
  damage_prevented_earthwarden?: number
  damage_prevented_mage?: number
  damage_prevented_paladin?: number
  damage_prevented_protector?: number
  damage_prevented_pyromancer?: number
  damage_prevented_shaman?: number
  damage_prevented_thunderlord?: number
  damage_prevented_warrior?: number
  damage_protector?: number
  damage_pyromancer?: number
  damage_shaman?: number
  damage_taken?: number
  damage_thunderlord?: number
  damage_warrior?: number
  deaths?: number
  defender_plays?: number
  dom_point_captures?: number
  dom_point_defends?: number
  earthwarden_plays?: number
  energyPowerups?: boolean
  flag_conquer_self?: number
  flag_conquer_team?: number
  flag_returns?: number
  heal?: number
  heal_aquamancer?: number
  heal_avenger?: number
  heal_berserker?: number
  heal_crusader?: number
  heal_cryomancer?: number
  heal_defender?: number
  heal_earthwarden?: number
  heal_mage?: number
  heal_paladin?: number
  heal_protector?: number
  heal_pyromancer?: number
  heal_shaman?: number
  heal_thunderlord?: number
  heal_warrior?: number
  hide_prestige?: boolean
  hints?: boolean
  hotkeymode?: boolean
  kills?: number
  kills_capturetheflag?: number
  kills_domination?: number
  kills_teamdeathmatch?: number
  life_leeched?: number
  life_leeched_berserker?: number
  life_leeched_warrior?: number
  losses?: number
  losses_aquamancer?: number
  losses_avenger?: number
  losses_berserker?: number
  losses_crusader?: number
  losses_cryomancer?: number
  losses_defender?: number
  losses_mage?: number
  losses_paladin?: number
  losses_pyromancer?: number
  losses_shaman?: number
  losses_thunderlord?: number
  losses_warrior?: number
  mage_armor_selection?: number
  mage_cooldown?: number
  mage_critchance?: number
  mage_critmultiplier?: number
  mage_energy?: number
  mage_health?: number
  mage_helmet_selection?: number
  mage_plays?: number
  mage_skill1?: number
  mage_skill2?: number
  mage_skill3?: number
  mage_skill4?: number
  mage_skill5?: number
  mage_spec?: string
  magic_dust?: number
  mvp_count?: number
  packages?: string[]
  paladin_armor_selection?: number
  paladin_cooldown?: number
  paladin_critchance?: number
  paladin_critmultiplier?: number
  paladin_energy?: number
  paladin_health?: number
  paladin_helmet_selection?: number
  paladin_plays?: number
  paladin_skill1?: number
  paladin_skill2?: number
  paladin_skill3?: number
  paladin_skill4?: number
  paladin_skill5?: number
  paladin_spec?: string
  penalty?: number
  play_streak?: number
  powerups_collected?: number
  protector_plays?: number
  pyromancer_plays?: number
  repaired?: number
  repaired_common?: number
  repaired_epic?: number
  repaired_legendary?: number
  repaired_rare?: number
  reroll?: number
  reroll_legendary?: number
  reward_inventory?: number
  salvaged_dust_reward?: number
  salvaged_shards_reward?: number
  salvaged_weapons?: number
  salvaged_weapons_common?: number
  salvaged_weapons_epic?: number
  salvaged_weapons_legendary?: number
  salvaged_weapons_rare?: number
  selected_mount?: string
  shaman_armor_selection?: number
  shaman_cooldown?: number
  shaman_critchance?: number
  shaman_critmultiplier?: number
  shaman_energy?: number
  shaman_health?: number
  shaman_helmet_selection?: number
  shaman_plays?: number
  shaman_skill1?: number
  shaman_skill2?: number
  shaman_skill3?: number
  shaman_skill4?: number
  shaman_skill5?: number
  shaman_spec?: string
  simplifiedresourcepack?: boolean
  thunderlord_plays?: number
  total_domination_score?: number
  upgrade_crafted?: number
  upgrade_crafted_legendary?: number
  upgrade_random?: number
  upgrade_random_epic?: number
  void_shards?: number
  warrior_armor_selection?: number
  warrior_cooldown?: number
  warrior_critchance?: number
  warrior_critmultiplier?: number
  warrior_energy?: number
  warrior_health?: number
  warrior_helmet_selection?: number
  warrior_plays?: number
  warrior_skill1?: number
  warrior_skill2?: number
  warrior_skill3?: number
  warrior_skill4?: number
  warrior_skill5?: number
  warrior_spec?: string
  weapon_inventory?: BattlegroundWeaponInventory[]
  win_streak?: number
  wins?: number
  wins_aquamancer?: number
  wins_avenger?: number
  wins_berserker?: number
  wins_blu?: number
  wins_capturetheflag?: number
  wins_capturetheflag_a?: number
  wins_capturetheflag_b?: number
  wins_capturetheflag_blu?: number
  wins_capturetheflag_red?: number
  wins_crusader?: number
  wins_cryomancer?: number
  wins_defender?: number
  wins_domination?: number
  wins_domination_a?: number
  wins_domination_b?: number
  wins_domination_blu?: number
  wins_domination_red?: number
  wins_earthwarden?: number
  wins_mage?: number
  wins_paladin?: number
  wins_protector?: number
  wins_pyromancer?: number
  wins_red?: number
  wins_shaman?: number
  wins_teamdeathmatch?: number
  wins_teamdeathmatch_a?: number
  wins_teamdeathmatch_b?: number
  wins_teamdeathmatch_blu?: number
  wins_teamdeathmatch_red?: number
  wins_thunderlord?: number
  wins_warrior?: number
}

export interface BattlegroundWeaponInventory {
  ability?: number
  abilityBoost?: number
  category?: 'COMMON' | 'EPIC' | 'LEGENDARY' | 'RARE'
  chance?: number
  cooldown?: number
  crafted?: boolean
  damage?: number
  energy?: number
  health?: number
  id?: number
  material?: string
  movement?: number
  multiplier?: number
  spec?: {
    playerClass?: number
    spec?: number
  }
  upgradeMax?: number
  upgradeTimes?: number
  playStreak?: boolean
}
