import { IndexType } from '../../shared/util'

export type GingerBread = IndexType & {
  banana_hits_received?: number
  banana_hits_sent?: number
  blue_torpedo_hit?: number
  booster_active?: string
  box_pickups?: number
  box_pickups_canyon?: number
  box_pickups_hypixelgp?: number
  box_pickups_junglerush?: number
  box_pickups_monthly_a?: number
  box_pickups_monthly_b?: number
  box_pickups_olympus?: number
  box_pickups_retro?: number
  box_pickups_weekly_a?: number
  box_pickups_weekly_b?: number
  bronze_trophy?: number
  bronze_trophy_canyon?: number
  bronze_trophy_hypixelgp?: number
  bronze_trophy_junglerush?: number
  bronze_trophy_monthly_a?: number
  bronze_trophy_monthly_b?: number
  bronze_trophy_olympus?: number
  bronze_trophy_retro?: number
  bronze_trophy_weekly_a?: number
  bronze_trophy_weekly_b?: number
  canyon_plays?: number
  coins?: number
  coins_picked_up?: number
  engine_active?: string
  frame_active?: string
  gold_trophy?: number
  gold_trophy_canyon?: number
  gold_trophy_hypixelgp?: number
  gold_trophy_junglerush?: number
  gold_trophy_monthly_a?: number
  gold_trophy_monthly_b?: number
  gold_trophy_olympus?: number
  gold_trophy_retro?: number
  gold_trophy_weekly_a?: number
  gold_trophy_weekly_b?: number
  helmet_active?: string
  horn?: string
  hypixelgp_plays?: number
  jacket_active?: string
  junglerush_plays?: number
  laps_completed?: number
  lastTourneyAd?: number
  olympus_plays?: number
  packages?: string[]
  pants_active?: string
  particle_trail?: string
  parts?: string
  retro_plays?: number
  shoes_active?: string
  silver_trophy?: number
  silver_trophy_canyon?: number
  silver_trophy_hypixelgp?: number
  silver_trophy_junglerush?: number
  silver_trophy_monthly_a?: number
  silver_trophy_monthly_b?: number
  silver_trophy_olympus?: number
  silver_trophy_retro?: number
  silver_trophy_weekly_a?: number
  silver_trophy_weekly_b?: number
  skin_active?: string
  wins?: number
}
