export interface Mcgo {
  body_armor_cost?: number
  bombs_defused?: number
  bombs_defused_tourney_mcgo_defusal_0?: number
  bombs_planted?: number
  bombs_planted_tourney_mcgo_defusal_0?: number
  bounty_hunter?: number
  carbine_cost_reduction?: number
  carbine_damage_increase?: number
  carbine_recoil_reduction?: number
  carbine_reload_speed_reduction?: number
  coins?: number
  cop_kills?: number
  cop_kills_deathmatch?: number
  cop_kills_tourney_mcgo_defusal_0?: number
  criminal_kills?: number
  criminal_kills_deathmatch?: number
  criminal_kills_tourney_mcgo_defusal_0?: number
  deaths?: number
  deaths_deathmatch?: number
  deaths_tourney_mcgo_defusal_0?: number
  game_plays?: number
  game_plays_deathmatch?: number
  game_plays_tourney_mcgo_defusal_0?: number
  game_wins?: number
  game_wins_alleyway?: number
  game_wins_atomic?: number
  game_wins_carrier?: number
  game_wins_deathmatch?: number
  'game_wins_melon factory'?: number
  game_wins_overgrown?: number
  game_wins_reserve?: number
  game_wins_sandstorm?: number
  game_wins_temple?: number
  game_wins_tourney_mcgo_defusal_0?: number
  grenade_kills?: number
  grenade_kills_tourney_mcgo_defusal_0?: number
  grenadeKills?: number
  headshot_kills?: number
  headshot_kills_tourney_mcgo_defusal_0?: number
  kills?: number
  kills_2_11_2014?: number
  kills_3_10_2014?: number
  kills_3_11_2014?: number
  kills_4_11_2014?: number
  kills_5_10_2014?: number
  kills_10_2014?: number
  kills_11_2014?: number
  kills_deathmatch?: number
  kills_tourney_mcgo_defusal_0?: number
  killsNew?: number
  killsNew_2_11_2014?: number
  killsNew_3_11_2014?: number
  killsNew_4_11_2014?: number
  killsNew_5_10_2014?: number
  killsNew_10_2014?: number
  killsNew_11_2014?: number
  knife_attack_delay?: number
  knife_damage_increase?: number
  lastTourneyAd?: number
  magnum_cost_reduction?: number
  magnum_damage_increase?: number
  magnum_recoil_reduction?: number
  magnum_reload_speed_reduction?: number
  mcgo?: McgoClass
  monthly_kills_a?: number
  monthly_kills_b?: number
  packages?: string[]
  pistol_damage_increase?: number
  pistol_recoil_reduction?: number
  pistol_reload_speed_reduction?: number
  pocket_change?: number
  rifle_cost_reduction?: number
  rifle_damage_increase?: number
  rifle_recoil_reduction?: number
  rifle_reload_speed_reduction?: number
  round_wins?: number
  round_wins_tourney_mcgo_defusal_0?: number
  selected_lobby_prefix?: string
  selectedCarbineDev?: string
  selectedCreeperChestplateDev?: string
  selectedCreeperHelmetDev?: string
  selectedKnifeDev?: string
  selectedMagnumDev?: string
  selectedOcelotChestplateDev?: string
  selectedOcelotHelmetDev?: string
  selectedPistolDev?: string
  selectedRifleDev?: string
  selectedShotgunDev?: string
  selectedSmgDev?: string
  setting_animated_smoke?: boolean
  shotgun_cost_reduction?: number
  shotgun_damage_increase?: number
  shotgun_recoil_reduction?: number
  shotgun_reload_speed_reduction?: number
  shots_fired?: number
  shots_fired_tourney_mcgo_defusal_0?: number
  show_lobby_prefix?: boolean
  smg_cost_reduction?: number
  smg_damage_increase?: number
  smg_recoil_reduction?: number
  smg_reload_speed_reduction?: number
  strength_training?: number
  weekly_kills_a?: number
  weekly_kills_b?: number
}

export interface McgoClass {
  points?: number
}
