export interface SkyClash {
  active_class?: number
  archer_inventory?: { [key: string]: string }
  assassin_inventory?: { [key: string]: string }
  assists?: number
  assists_kit_assassin?: number
  assists_kit_swordsman?: number
  bow_hits?: number
  bow_hits_kit_archer?: number
  bow_hits_kit_assassin?: number
  bow_hits_kit_swordsman?: number
  bow_kills?: number
  bow_kills_kit_assassin?: number
  bow_shots?: number
  bow_shots_kit_archer?: number
  bow_shots_kit_assassin?: number
  bow_shots_kit_necromancer?: number
  bow_shots_kit_swordsman?: number
  card_packs?: number
  class_0?: string
  class_2?: string
  class_3?: string
  classes_unlocked?: number
  coins?: number
  cute_pants_found?: number
  cute_pants_found_kit_archer?: number
  cute_pants_found_kit_swordsman?: number
  deaths?: number
  deaths_doubles?: number
  deaths_four_teams?: number
  deaths_kit_archer?: number
  deaths_kit_assassin?: number
  deaths_kit_necromancer?: number
  deaths_kit_swordsman?: number
  deaths_perk_creeper?: number
  deaths_perk_elven_archer?: number
  deaths_perk_endless_quiver?: number
  deaths_perk_explosive_bow?: number
  deaths_perk_fruit_finder?: number
  deaths_perk_headstart?: number
  deaths_perk_hearty_start?: number
  deaths_perk_hit_and_run?: number
  deaths_perk_honed_bow?: number
  deaths_perk_marksman?: number
  deaths_perk_pearl_absorption?: number
  deaths_perk_rampage?: number
  deaths_perk_regeneration?: number
  deaths_perk_sharpened_sword?: number
  deaths_perk_snow_golem?: number
  deaths_perk_witch?: number
  deaths_solo?: number
  deaths_team_war?: number
  doubles_wins?: number
  doubles_wins_kit_assassin?: number
  doubles_wins_kit_swordsman?: number
  enderchests_opened?: number
  enderchests_opened_kit_archer?: number
  enderchests_opened_kit_assassin?: number
  enderchests_opened_kit_necromancer?: number
  enderchests_opened_kit_swordsman?: number
  fastest_win_doubles?: number
  fastest_win_doubles_kit_assassin?: number
  fastest_win_doubles_kit_swordsman?: number
  fastest_win_four_teams?: number
  fastest_win_four_teams_kit_assassin?: number
  fastest_win_mega?: number
  fastest_win_mega_kit_assassin?: number
  fastest_win_solo?: number
  fastest_win_solo_kit_archer?: number
  fastest_win_solo_kit_assassin?: number
  fastest_win_solo_kit_swordsman?: number
  fastest_win_team_war?: number
  fastest_win_team_war_kit_archer?: number
  fastest_win_team_war_kit_assassin?: number
  four_teams_wins?: number
  four_teams_wins_kit_assassin?: number
  games?: number
  games_played?: number
  games_played_kit_archer?: number
  games_played_kit_assassin?: number
  games_played_kit_necromancer?: number
  games_played_kit_swordsman?: number
  highestKillstreak?: number
  kills?: number
  kills_doubles?: number
  kills_four_teams?: number
  kills_kit_archer?: number
  kills_kit_assassin?: number
  kills_kit_swordsman?: number
  kills_mega?: number
  kills_monthly_a?: number
  kills_monthly_b?: number
  kills_perk_elven_archer?: number
  kills_perk_endless_quiver?: number
  kills_perk_energy_drink?: number
  kills_perk_explosive_bow?: number
  kills_perk_fruit_finder?: number
  kills_perk_headstart?: number
  kills_perk_hearty_start?: number
  kills_perk_hit_and_run?: number
  kills_perk_honed_bow?: number
  kills_perk_marksman?: number
  kills_perk_pearl_absorption?: number
  kills_perk_rampage?: number
  kills_perk_regeneration?: number
  kills_perk_sharpened_sword?: number
  kills_perk_winged_boots?: number
  kills_solo?: number
  kills_team_war?: number
  kills_weekly_a?: number
  kills_weekly_b?: number
  killstreak?: number
  kit_assassin_master?: number
  kit_assassin_minor?: number
  kit_swordsman_minor?: number
  longest_bow_kill?: number
  longest_bow_kill_kit_assassin?: number
  longest_bow_shot?: number
  longest_bow_shot_kit_archer?: number
  longest_bow_shot_kit_assassin?: number
  longest_bow_shot_kit_swordsman?: number
  losses?: number
  losses_doubles?: number
  losses_four_teams?: number
  losses_perk_creeper?: number
  losses_perk_elven_archer?: number
  losses_perk_endless_quiver?: number
  losses_perk_explosive_bow?: number
  losses_perk_fruit_finder?: number
  losses_perk_headstart?: number
  losses_perk_hearty_start?: number
  losses_perk_hit_and_run?: number
  losses_perk_honed_bow?: number
  losses_perk_marksman?: number
  losses_perk_pearl_absorption?: number
  losses_perk_rampage?: number
  losses_perk_regeneration?: number
  losses_perk_sharpened_sword?: number
  losses_perk_snow_golem?: number
  losses_perk_witch?: number
  losses_solo?: number
  losses_team_war?: number
  mega_wins?: number
  mega_wins_kit_assassin?: number
  melee_kills?: number
  melee_kills_kit_archer?: number
  melee_kills_kit_assassin?: number
  melee_kills_kit_swordsman?: number
  mob_kills?: number
  mob_kills_kit_archer?: number
  mob_kills_kit_assassin?: number
  mobs_killed?: number
  mobs_killed_kit_archer?: number
  mobs_killed_kit_assassin?: number
  mobs_killed_kit_necromancer?: number
  mobs_killed_kit_swordsman?: number
  mobs_spawned?: number
  mobs_spawned_kit_archer?: number
  mobs_spawned_kit_assassin?: number
  mobs_spawned_kit_necromancer?: number
  mobs_spawned_kit_swordsman?: number
  most_kills_game?: number
  most_kills_game_kit_archer?: number
  most_kills_game_kit_assassin?: number
  most_kills_game_kit_swordsman?: number
  necromancer_inventory?: { [key: string]: string }
  packages?: string[]
  perk_alchemy?: number
  perk_alchemy_duplicates?: number
  perk_alchemy_new?: boolean
  perk_archer_challenge?: number
  perk_archer_challenge_new?: boolean
  perk_arrow_deflection?: number
  perk_arrow_deflection_duplicates?: number
  perk_arrow_deflection_new?: boolean
  perk_bat_shield?: number
  perk_bat_shield_duplicates?: number
  perk_bat_shield_new?: boolean
  perk_bigger_bangs?: number
  perk_bigger_bangs_duplicates?: number
  perk_bigger_bangs_new?: boolean
  perk_blast_protection?: number
  perk_blast_protection_duplicates?: number
  perk_blast_protection_new?: boolean
  perk_blazing_arrows?: number
  perk_blazing_arrows_duplicates?: number
  perk_blazing_arrows_new?: boolean
  perk_bounty_hunter?: number
  perk_bounty_hunter_duplicates?: number
  perk_bounty_hunter_new?: boolean
  perk_chicken_bow?: number
  perk_chicken_bow_duplicates?: number
  perk_chicken_bow_new?: boolean
  perk_creeper?: number
  perk_creeper_duplicates?: number
  perk_creeper_new?: boolean
  perk_damage_potion?: number
  perk_damage_potion_duplicates?: number
  perk_damage_potion_new?: boolean
  perk_double_jump?: number
  perk_double_jump_duplicates?: number
  perk_double_jump_new?: boolean
  perk_elven_archer?: number
  perk_elven_archer_duplicates?: number
  perk_elven_archer_new?: boolean
  perk_enderman?: number
  perk_enderman_duplicates?: number
  perk_enderman_new?: boolean
  perk_endless_quiver?: number
  perk_endless_quiver_duplicates?: number
  perk_endless_quiver_new?: boolean
  perk_energy_drink?: number
  perk_energy_drink_duplicates?: number
  perk_energy_drink_new?: boolean
  perk_explosive_bow?: number
  perk_explosive_bow_duplicates?: number
  perk_explosive_bow_new?: boolean
  perk_flower_power?: number
  perk_flower_power_duplicates?: number
  perk_flower_power_new?: boolean
  perk_fruit_finder?: number
  perk_fruit_finder_duplicates?: number
  perk_fruit_finder_new?: boolean
  perk_guardian?: number
  perk_guardian_duplicates?: number
  perk_guardian_new?: boolean
  perk_head_hunter?: number
  perk_head_hunter_new?: boolean
  perk_headstart?: number
  perk_headstart_new?: boolean
  perk_hearty_start?: number
  perk_hearty_start_duplicates?: number
  perk_hit_and_run?: number
  perk_hit_and_run_duplicates?: number
  perk_honed_bow?: number
  perk_honed_bow_duplicates?: number
  perk_honed_bow_new?: boolean
  perk_invisibility?: number
  perk_invisibility_duplicates?: number
  perk_invisibility_new?: boolean
  perk_iron_golem?: number
  perk_iron_golem_duplicates?: number
  perk_iron_golem_new?: boolean
  perk_lifesteal?: number
  perk_lifesteal_duplicates?: number
  perk_lifesteal_new?: boolean
  perk_marksman?: number
  perk_marksman_duplicates?: number
  perk_monster_hunter?: number
  perk_monster_hunter_duplicates?: number
  perk_monster_hunter_new?: boolean
  perk_mushroom_aura?: number
  perk_mushroom_aura_duplicates?: number
  perk_mushroom_aura_new?: boolean
  perk_no_chest_challenge?: number
  perk_no_chest_challenge_new?: boolean
  perk_nuclear_solution?: number
  perk_nuclear_solution_duplicates?: number
  perk_nuclear_solution_new?: boolean
  perk_nutritious?: number
  perk_nutritious_duplicates?: number
  perk_nutritious_new?: boolean
  perk_pacify?: number
  perk_pacify_duplicates?: number
  perk_pacify_new?: boolean
  perk_pearl_absorption?: number
  perk_pearl_absorption_duplicates?: number
  perk_pearl_absorption_new?: boolean
  perk_rampage?: number
  perk_rampage_duplicates?: number
  perk_regeneration?: number
  perk_regeneration_duplicates?: number
  perk_resistant?: number
  perk_resistant_duplicates?: number
  perk_sharpened_sword?: number
  perk_sharpened_sword_duplicates?: number
  perk_sharpened_sword_new?: boolean
  perk_skeleton_jockey?: number
  perk_skeleton_jockey_duplicates?: number
  perk_skeleton_jockey_new?: boolean
  perk_snow_golem?: number
  perk_snow_golem_duplicates?: number
  perk_snow_golem_new?: boolean
  perk_sugar_rush?: number
  perk_sugar_rush_duplicates?: number
  perk_sugar_rush_new?: boolean
  perk_supply_drop?: number
  perk_supply_drop_duplicates?: number
  perk_supply_drop_new?: boolean
  perk_tripleshot?: number
  perk_tripleshot_duplicates?: number
  perk_tripleshot_new?: boolean
  perk_void_chest?: number
  perk_void_chest_duplicates?: number
  perk_void_chest_new?: boolean
  perk_void_magnet?: number
  perk_void_magnet_duplicates?: number
  perk_void_magnet_new?: boolean
  perk_void_warranty?: number
  perk_void_warranty_duplicates?: number
  perk_void_warranty_new?: boolean
  perk_winged_boots?: number
  perk_winged_boots_new?: boolean
  perk_witch?: number
  perk_witch_duplicates?: number
  perk_witch_new?: boolean
  play_streak?: number
  playstreak?: number
  quits?: number
  solo_wins?: number
  solo_wins_kit_archer?: number
  solo_wins_kit_assassin?: number
  solo_wins_kit_swordsman?: number
  spawn_at_witch?: number
  swordsman_inventory?: { [key: string]: string }
  team_war_wins?: number
  team_war_wins_kit_archer?: number
  team_war_wins_kit_assassin?: number
  void_kills?: number
  void_kills_kit_archer?: number
  void_kills_kit_assassin?: number
  void_kills_kit_swordsman?: number
  win_streak?: number
  wins?: number
  wins_doubles?: number
  wins_four_teams?: number
  wins_mega?: number
  wins_perk_endless_quiver?: number
  wins_perk_energy_drink?: number
  wins_perk_explosive_bow?: number
  wins_perk_fruit_finder?: number
  wins_perk_headstart?: number
  wins_perk_hit_and_run?: number
  wins_perk_honed_bow?: number
  wins_perk_pearl_absorption?: number
  wins_perk_rampage?: number
  wins_perk_regeneration?: number
  wins_perk_sharpened_sword?: number
  wins_perk_winged_boots?: number
  wins_solo?: number
  wins_team_war?: number
}
