export interface SpeedUHC {
  active_cage?: string
  active_killeffect?: string
  active_projectiletrail?: string
  active_victorydance?: string
  activeKit_INSANE?: string
  activeKit_NORMAL?: string
  activeMasterPerk?: string
  arrows_hit?: number
  arrows_shot?: number
  assists?: number
  assists_insane?: number
  assists_kit_basic_insane_default?: number
  assists_kit_basic_insane_miner?: number
  assists_kit_basic_normal_archaeologist?: number
  assists_kit_basic_normal_default?: number
  assists_kit_basic_normal_knight?: number
  assists_kit_basic_normal_scout?: number
  assists_kit_basic_normal_summoner?: number
  assists_normal?: number
  assists_solo?: number
  assists_team?: number
  blocks_broken?: number
  blocks_placed?: number
  coins?: number
  deaths?: number
  deaths_insane?: number
  deaths_kit_basic_insane_archer?: number
  deaths_kit_basic_insane_default?: number
  deaths_kit_basic_insane_healer?: number
  deaths_kit_basic_insane_scout?: number
  deaths_kit_basic_normal_archaeologist?: number
  deaths_kit_basic_normal_archer?: number
  deaths_kit_basic_normal_default?: number
  deaths_kit_basic_normal_enchanter?: number
  deaths_kit_basic_normal_healer?: number
  deaths_kit_basic_normal_knight?: number
  deaths_kit_basic_normal_scout?: number
  deaths_kit_basic_normal_summoner?: number
  deaths_mastery_fortune?: number
  deaths_mastery_huntsman?: number
  deaths_mastery_wild_specialist?: number
  deaths_normal?: number
  deaths_solo?: number
  deaths_solo_insane?: number
  deaths_solo_normal?: number
  deaths_team?: number
  deaths_team_insane?: number
  deaths_team_normal?: number
  enderpearls_thrown?: number
  extra_wheels?: number
  firstJoinLobby?: boolean
  firstJoinLobbyInt?: number
  found_COMMON?: number
  found_LEGENDARY?: number
  found_RARE?: number
  games?: number
  games_insane?: number
  games_kit_basic_insane_archer?: number
  games_kit_basic_insane_default?: number
  games_kit_basic_insane_healer?: number
  games_kit_basic_insane_miner?: number
  games_kit_basic_insane_scout?: number
  games_kit_basic_normal_archaeologist?: number
  games_kit_basic_normal_archer?: number
  games_kit_basic_normal_default?: number
  games_kit_basic_normal_knight?: number
  games_kit_basic_normal_scout?: number
  games_kit_basic_normal_summoner?: number
  games_normal?: number
  games_solo?: number
  games_team?: number
  highestKillstreak?: number
  highestWinstreak?: number
  insane_adrenaline?: number
  insane_knowledge?: number
  insane_low_gravity?: number
  insane_master_breeder?: number
  insane_no_mercy?: number
  insane_notoriety?: number
  insane_portal_protection?: number
  insane_swimming_champion?: number
  insane_tank?: number
  insane_telekinesis?: number
  insane_vitamins?: number
  iron_chestplate_drop?: number
  items_enchanted?: number
  kills?: number
  kills_insane?: number
  kills_kit_basic_insane_archer?: number
  kills_kit_basic_insane_default?: number
  kills_kit_basic_insane_healer?: number
  kills_kit_basic_insane_miner?: number
  kills_kit_basic_normal_archaeologist?: number
  kills_kit_basic_normal_archer?: number
  kills_kit_basic_normal_default?: number
  kills_kit_basic_normal_healer?: number
  kills_kit_basic_normal_knight?: number
  kills_kit_basic_normal_scout?: number
  kills_mastery_fortune?: number
  kills_mastery_huntsman?: number
  kills_mastery_wild_specialist?: number
  kills_monthly_a?: number
  kills_monthly_b?: number
  kills_normal?: number
  kills_solo?: number
  kills_solo_insane?: number
  kills_solo_normal?: number
  kills_team?: number
  kills_team_insane?: number
  kills_team_normal?: number
  kills_weekly_a?: number
  kills_weekly_b?: number
  killstreak?: number
  killstreak_insane?: number
  killstreak_kit_basic_insane_archer?: number
  killstreak_kit_basic_insane_default?: number
  killstreak_kit_basic_insane_healer?: number
  killstreak_kit_basic_insane_miner?: number
  killstreak_kit_basic_normal_archaeologist?: number
  killstreak_kit_basic_normal_archer?: number
  killstreak_kit_basic_normal_default?: number
  killstreak_kit_basic_normal_knight?: number
  killstreak_kit_basic_normal_scout?: number
  killstreak_normal?: number
  killstreak_solo?: number
  killstreak_team?: number
  losses?: number
  losses_insane?: number
  losses_kit_basic_insane_archer?: number
  losses_kit_basic_insane_default?: number
  losses_kit_basic_insane_healer?: number
  losses_kit_basic_normal_archaeologist?: number
  losses_kit_basic_normal_archer?: number
  losses_kit_basic_normal_default?: number
  losses_kit_basic_normal_enchanter?: number
  losses_kit_basic_normal_healer?: number
  losses_kit_basic_normal_knight?: number
  losses_kit_basic_normal_scout?: number
  losses_kit_basic_normal_summoner?: number
  losses_mastery_fortune?: number
  losses_mastery_huntsman?: number
  losses_mastery_wild_specialist?: number
  losses_normal?: number
  losses_solo?: number
  losses_solo_insane?: number
  losses_solo_normal?: number
  losses_team?: number
  losses_team_insane?: number
  losses_team_normal?: number
  mastery_fortune?: number
  mastery_huntsman?: number
  movedOver?: boolean
  normal_arrow_recovery?: number
  normal_bow_flex?: number
  normal_cold_blood?: number
  normal_expert_miner?: number
  normal_low_gravity?: number
  normal_marksmob?: number
  normal_master_brewer?: number
  normal_medicine?: number
  normal_monster_tamer?: number
  normal_no_mercy?: number
  normal_nourishment?: number
  normal_portal_protection?: number
  normal_swimming_champion?: number
  normal_telekinesis?: number
  normal_tenacity?: number
  normal_vitamins?: number
  packages?: string[]
  quits?: number
  salt?: number
  score?: number
  score_kit_basic_normal_archaeologist?: number
  score_kit_basic_normal_archer?: number
  score_kit_basic_normal_default?: number
  score_kit_basic_normal_healer?: number
  score_kit_basic_normal_knight?: number
  score_normal?: number
  score_solo?: number
  score_team?: number
  survived_players?: number
  survived_players_insane?: number
  survived_players_kit_basic_insane_archer?: number
  survived_players_kit_basic_insane_default?: number
  survived_players_kit_basic_insane_healer?: number
  survived_players_kit_basic_insane_miner?: number
  survived_players_kit_basic_insane_scout?: number
  survived_players_kit_basic_normal_archaeologist?: number
  survived_players_kit_basic_normal_archer?: number
  survived_players_kit_basic_normal_default?: number
  survived_players_kit_basic_normal_healer?: number
  survived_players_kit_basic_normal_knight?: number
  survived_players_kit_basic_normal_scout?: number
  survived_players_kit_basic_normal_summoner?: number
  survived_players_normal?: number
  survived_players_solo?: number
  survived_players_team?: number
  tears?: number
  tears_gathered?: number
  tearWellUses?: number
  win_streak?: number
  wins?: number
  wins_insane?: number
  wins_kit_basic_insane_archer?: number
  wins_kit_basic_insane_default?: number
  wins_kit_basic_insane_healer?: number
  wins_kit_basic_insane_miner?: number
  wins_kit_basic_insane_scout?: number
  wins_kit_basic_normal_archaeologist?: number
  wins_kit_basic_normal_archer?: number
  wins_kit_basic_normal_default?: number
  wins_kit_basic_normal_knight?: number
  wins_kit_basic_normal_scout?: number
  wins_kit_basic_normal_summoner?: number
  wins_mastery_fortune?: number
  wins_mastery_huntsman?: number
  wins_mastery_wild_specialist?: number
  wins_normal?: number
  wins_solo?: number
  wins_solo_insane?: number
  wins_solo_normal?: number
  wins_team?: number
  wins_team_insane?: number
  wins_team_normal?: number
  winstreak?: number
  winstreak_insane?: number
  winstreak_kit_basic_insane_archer?: number
  winstreak_kit_basic_insane_default?: number
  winstreak_kit_basic_insane_healer?: number
  winstreak_kit_basic_insane_miner?: number
  winstreak_kit_basic_insane_scout?: number
  winstreak_kit_basic_normal_archaeologist?: number
  winstreak_kit_basic_normal_archer?: number
  winstreak_kit_basic_normal_default?: number
  winstreak_kit_basic_normal_knight?: number
  winstreak_kit_basic_normal_scout?: number
  winstreak_kit_basic_normal_summoner?: number
  winstreak_normal?: number
  winstreak_solo?: number
  winstreak_team?: number
}
