export interface TNTGames {
  active_death_effect?: string
  active_particle_effect?: string
  air_time_capture?: number
  assists_capture?: number
  bloodwizard_explode?: number
  bloodwizard_regen?: number
  capture_class?: string
  coins?: number
  deaths_bowspleef?: number
  deaths_capture?: number
  deaths_pvprun?: number
  deaths_tntrun?: number
  doublejump_tntrun?: number
  firewizard_explode?: number
  firewizard_regen?: number
  flags?: Flags
  icewizard_explode?: number
  icewizard_regen?: number
  kills_capture?: number
  kills_pvprun?: number
  kills_tntag?: number
  kinetic_healing_capture?: number
  kineticwizard_explode?: number
  kineticwizard_regen?: number
  new_active_death_effect?: string
  new_active_particle_effect?: string
  new_bloodwizard_assists?: number
  new_bloodwizard_deaths?: number
  new_bloodwizard_explode?: number
  new_bloodwizard_explode_legacy?: number
  new_bloodwizard_kills?: number
  new_bloodwizard_regen?: number
  new_bloodwizard_regen_legacy?: number
  new_double_jump_effect?: string
  new_firewizard_assists?: number
  new_firewizard_damage_taken?: number
  new_firewizard_deaths?: number
  new_firewizard_explode?: number
  new_firewizard_explode_legacy?: number
  new_firewizard_healing?: number
  new_firewizard_kills?: number
  new_firewizard_regen?: number
  new_firewizard_regen_legacy?: number
  new_icewizard_assists?: number
  new_icewizard_deaths?: number
  new_icewizard_explode?: number
  new_icewizard_explode_legacy?: number
  new_icewizard_regen?: number
  new_icewizard_regen_legacy?: number
  new_kineticwizard_assists?: number
  new_kineticwizard_damage_taken?: number
  new_kineticwizard_deaths?: number
  new_kineticwizard_explode?: number
  new_kineticwizard_explode_legacy?: number
  new_kineticwizard_healing?: number
  new_kineticwizard_kills?: number
  new_kineticwizard_regen?: number
  new_kineticwizard_regen_legacy?: number
  new_pvprun_double_jumps?: number
  new_pvprun_double_jumps_legacy?: number
  new_pvprun_fortitude?: number
  new_pvprun_notoriety?: number
  new_pvprun_regeneration?: number
  new_selected_hat?: string
  new_spleef_arrowtrail?: string
  new_spleef_double_jumps?: number
  new_spleef_double_jumps_legacy?: number
  new_spleef_repulsor?: number
  new_spleef_repulsor_legacy?: number
  new_spleef_tripleshot?: number
  new_spleef_tripleshot_legacy?: number
  new_stormwizard_assists?: number
  new_stormwizard_damage_taken?: number
  new_stormwizard_deaths?: number
  new_stormwizard_explode?: number
  new_stormwizard_healing?: number
  new_stormwizard_kills?: number
  new_stormwizard_regen?: number
  new_tntag_speedy?: number
  new_tntrun_double_jumps?: number
  new_tntrun_double_jumps_legacy?: number
  new_tntrun_slowness_potions?: number
  new_tntrun_speed_potions?: number
  new_toxicwizard_assists?: number
  new_toxicwizard_deaths?: number
  new_toxicwizard_explode?: number
  new_toxicwizard_explode_legacy?: number
  new_toxicwizard_kills?: number
  new_toxicwizard_regen?: number
  new_toxicwizard_regen_legacy?: number
  new_witherwizard_assists?: number
  new_witherwizard_damage_taken?: number
  new_witherwizard_deaths?: number
  new_witherwizard_explode?: number
  new_witherwizard_explode_legacy?: number
  new_witherwizard_healing?: number
  new_witherwizard_kills?: number
  new_witherwizard_regen?: number
  new_witherwizard_regen_legacy?: number
  packages?: string[]
  points_capture?: number
  privategames?: TNTGamesPrivategames
  record_pvprun?: number
  record_tntrun?: number
  run_potions_splashed_on_players?: number
  selected_hat?: string
  spleef_doublejump?: number
  spleef_repulse?: number
  spleef_triple?: number
  tag_blastprotection?: number
  tag_slowitdown?: number
  tag_speed?: number
  tag_speeditup?: number
  tags_bowspleef?: number
  votes_Spiral?: number
  'votes_TNT Run (A)'?: number
  wins?: number
  wins_bowspleef?: number
  wins_capture?: number
  wins_pvprun?: number
  wins_tntag?: number
  wins_tntrun?: number
  winstreak?: number
  witherwizard_explode?: number
  witherwizard_regen?: number
  wizards_selected_class?: string
}

export interface Flags {
  enable_explosive_dash?: boolean
  give_dj_feather?: boolean
  show_tip_holograms?: boolean
  show_tntrun_actionbar_info?: boolean
  show_tnttag_actionbar_info?: boolean
  show_wizards_actionbar_info?: boolean
  show_wizards_cooldown_notifications?: boolean
}

export interface TNTGamesPrivategames {
  low_gravity?: boolean
  maxed_perks?: boolean
  pvp_run_armor_type?: string
  pvp_run_knockback?: boolean
  pvp_run_sword_type?: string
  speed?: string
  tnt_run_snowballs?: boolean
  tnt_tag_deathmatch?: boolean
  tnt_tag_no_powerups?: boolean
}
