export interface TrueCombat {
  activeKit_Solo?: string
  activeKit_Solo_chaos?: string
  activeKit_Team_chaos?: string
  arrows_hit?: number
  arrows_shot?: number
  coins?: number
  crafting_lucky_brawler?: number
  crafting_lucky_enchanted_book_sharpness?: number
  crazywalls_deaths_solo?: number
  crazywalls_deaths_solo_chaos?: number
  crazywalls_deaths_team?: number
  crazywalls_deaths_team_chaos?: number
  crazywalls_games_solo?: number
  crazywalls_games_solo_chaos?: number
  crazywalls_games_team?: number
  crazywalls_games_team_chaos?: number
  crazywalls_kills_monthly_a_solo_chaos?: number
  crazywalls_kills_monthly_a_team_chaos?: number
  crazywalls_kills_monthly_b_solo?: number
  crazywalls_kills_monthly_b_solo_chaos?: number
  crazywalls_kills_monthly_b_team?: number
  crazywalls_kills_monthly_b_team_chaos?: number
  crazywalls_kills_solo?: number
  crazywalls_kills_solo_chaos?: number
  crazywalls_kills_team?: number
  crazywalls_kills_team_chaos?: number
  crazywalls_kills_weekly_a_solo?: number
  crazywalls_kills_weekly_a_solo_chaos?: number
  crazywalls_kills_weekly_a_team_chaos?: number
  crazywalls_kills_weekly_b_solo?: number
  crazywalls_kills_weekly_b_solo_chaos?: number
  crazywalls_kills_weekly_b_team?: number
  crazywalls_kills_weekly_b_team_chaos?: number
  crazywalls_losses_solo?: number
  crazywalls_losses_solo_chaos?: number
  crazywalls_losses_team?: number
  crazywalls_losses_team_chaos?: number
  crazywalls_wins_solo?: number
  crazywalls_wins_solo_chaos?: number
  crazywalls_wins_team_chaos?: number
  deaths?: number
  games?: number
  giant_zombie?: number
  giant_zombie_legendaries?: number
  giant_zombie_rares?: number
  gold_dust?: number
  golden_skulls?: number
  items_enchanted?: number
  kills?: number
  kills_monthly_a?: number
  kills_monthly_b?: number
  kills_weekly_a?: number
  kills_weekly_b?: number
  kit_basic_chaos_alchemist?: number
  kit_basic_chaos_armorer?: number
  kit_basic_chaos_knight?: number
  kit_basic_chaos_weaponsmith?: number
  live_combat?: boolean
  losses?: number
  packages?: string[]
  show_noob_holograms?: boolean
  skulls_gathered?: number
  solo_adrenaline?: number
  solo_blazing_arrow?: number
  solo_bounty_hunter?: number
  solo_chaos_adrenaline?: number
  solo_chaos_berserk?: number
  solo_chaos_blazing_arrow?: number
  solo_chaos_bounty_hunter?: number
  solo_chaos_businessman?: number
  solo_chaos_knowledge?: number
  solo_chaos_rusher?: number
  solo_chaos_smarty_pants?: number
  solo_chaos_super_luck?: number
  solo_chaos_tomb_robber?: number
  solo_chaos_vampirism?: number
  solo_knowledge?: number
  solo_lucky_drops?: number
  solo_precision?: number
  solo_rusher?: number
  solo_speed_mining?: number
  solo_swiftness?: number
  solo_vampirism?: number
  survived_players?: number
  team_adrenaline?: number
  'team_annoy-o-mite'?: number
  team_berserk?: number
  team_blazing_arrow?: number
  team_bounty_hunter?: number
  team_group_heal?: number
  team_last_stand?: number
  team_precision?: number
  team_rusher?: number
  team_smart_mining?: number
  team_swiftness?: number
  votes_Garden?: number
  win_streak?: number
  wins?: number
}
