export interface UHCClass {
  cache3?: boolean
  clearup_achievement?: boolean
  coins?: number
  deaths?: number
  'deaths_red vs blue'?: number
  deaths_solo?: number
  equippedKit?: string
  heads_eaten?: number
  heads_eaten_solo?: number
  kills?: number
  kills_solo?: number
  kills_solo2?: number
  kills2?: number
  kit_ARCHERY_TOOLS?: number
  kit_ECOLOGIST?: number
  kit_LUNCH_BOX?: number
  kit_MAGIC_TOOLS?: number
  kit_WORKING_TOOLS?: number
  monthly_kills__a?: number
  monthly_kills__b?: number
  monthly_kills_a?: number
  monthly_kills_b?: number
  monthly_wins__a?: number
  monthly_wins_a?: number
  packages?: string[]
  perk_alchemy_line_a?: number
  perk_alchemy_line_b?: number
  perk_alchemy_line_c?: number
  perk_alchemy_prestige?: number
  perk_apprentice_line_a?: number
  perk_apprentice_line_b?: number
  perk_apprentice_line_c?: number
  perk_armorsmith_line_a?: number
  perk_armorsmith_line_b?: number
  perk_armorsmith_line_c?: number
  perk_armorsmith_prestige?: number
  perk_bloodcraft_line_a?: number
  perk_bloodcraft_line_b?: number
  perk_bloodcraft_line_c?: number
  perk_bloodcraft_prestige?: number
  perk_cooking_line_a?: number
  perk_cooking_line_b?: number
  perk_cooking_line_c?: number
  perk_cooking_prestige?: number
  perk_enchanting_line_a?: number
  perk_enchanting_line_b?: number
  perk_enchanting_line_c?: number
  perk_enchanting_prestige?: number
  perk_engineering_line_a?: number
  perk_engineering_line_b?: number
  perk_engineering_line_c?: number
  perk_engineering_prestige?: number
  perk_hunter_line_a?: number
  perk_hunter_line_b?: number
  perk_hunter_line_c?: number
  perk_hunter_prestige?: number
  perk_invention_line_a?: number
  perk_invention_line_b?: number
  perk_invention_line_c?: number
  perk_survivalism_line_a?: number
  perk_survivalism_line_b?: number
  perk_survivalism_line_c?: number
  perk_survivalism_prestige?: number
  perk_toolsmithing_line_a?: number
  perk_toolsmithing_line_b?: number
  perk_toolsmithing_line_c?: number
  perk_toolsmithing_prestige?: number
  perk_weaponsmith_line_a?: number
  perk_weaponsmith_line_b?: number
  perk_weaponsmith_line_c?: number
  perk_weaponsmith_prestige?: number
  privategames?: UHCPrivategames
  saved_stats?: boolean
  score?: number
  ultimates_crafted?: number
  ultimates_crafted_solo?: number
  wins?: number
  wins_50v50?: number
  'wins_red vs blue'?: number
  wins_solo?: number
  wins_solo2?: number
  wins2?: number
}

export interface UHCPrivategames {
  all_recipes?: boolean
  border_shrink?: string
  game_length?: string
  grace_period?: string
  health?: string
  infinite_crafts?: boolean
  mode_type?: boolean
  team_size?: string
}
