export interface Walls {
  adrenaline?: number
  artisan?: number
  assists?: number
  attractor?: number
  bacon?: number
  berserk?: number
  blacksmith?: number
  blacksmith_starter?: number
  blood?: boolean
  bomberman?: number
  boss_digger?: number
  boss_guardian?: number
  boss_skills?: number
  burn_baby_burn?: number
  canadian?: number
  chainkiller?: number
  chef?: number
  chemist?: number
  coins?: number
  creeper_egg?: number
  deaths?: number
  dwarwen_skills?: number
  ecologist?: number
  einstein?: number
  expert_miner?: number
  final_form?: number
  fireproof?: number
  fisherman?: number
  fortune?: number
  gold_rush?: number
  guitarist?: number
  haste?: number
  hunter?: number
  insane_farmer?: number
  Inventory?: { [key: string]: string }
  InventoryLayout2?: { [key: string]: string }
  kills?: number
  lazyman?: number
  leather_worker?: number
  losses?: number
  master_troll?: number
  monthly_assists_a?: number
  monthly_assists_b?: number
  monthly_kills_a?: number
  monthly_kills_b?: number
  monthly_wins_a?: number
  monthly_wins_b?: number
  opportunity?: number
  packages?: string[]
  pyromaniac?: number
  ready?: number
  sage?: number
  scotsman?: number
  skybase_king?: number
  smart_boy?: number
  snack_lover?: number
  soup_drinker?: number
  step?: number
  swift?: number
  tenacity?: number
  thats_hot?: number
  tragedy?: number
  vampirism?: number
  vitality?: number
  votes_Shire?: number
  weekly_assists_a?: number
  weekly_assists_b?: number
  weekly_kills_a?: number
  weekly_kills_b?: number
  weekly_wins_a?: number
  weekly_wins_b?: number
  wins?: number
}
